version: "3.8"

services:
  api:
    build: .
    container_name: manga_api
    ports:
      - "8001:8001"
    volumes:
      - ./app/db:/app/db
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  web:
    image: nginx:alpine
    container_name: motorizadoX
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources:/usr/share/nginx/html/static
    depends_on:
      - api